<?php
declare(strict_types=1);
use PuneMirror\Core\JsonStore;use PuneMirror\Core\UrlGuard;use PuneMirror\Core\UuidV7;use PuneMirror\Runtime\FileRuntimeStore;use PuneMirror\Services\CredentialVault;use PuneMirror\Services\ErrorCenterService;use PuneMirror\Services\QuotaService;use PuneMirror\Services\RateLimiter;
$app=require dirname(__DIR__).'/bootstrap/app.php';$root=$app['root'];$c=$app['config'];$store=new JsonStore($root.'/storage/data');$assert=function(bool $ok,string $label){if(!$ok){fwrite(STDERR,"FAIL: $label\n");exit(1);}echo "PASS: $label\n";};
$id=UuidV7::generate();$vault=new CredentialVault($root.'/storage/secrets',(string)$c['security']['app_key']);$masked=$vault->put($id,['access_token'=>'super-secret-123456']);$assert(($vault->all($id)['access_token']??'')==='super-secret-123456','credential vault decrypts encrypted secret');$assert(str_ends_with($masked['access_token']??'','3456'),'credential vault returns masked value');$vault->delete($id);
$blocked=false;try{UrlGuard::assertPublicHttpUrl('http://127.0.0.1/admin');}catch(Throwable){$blocked=true;}$assert($blocked,'SSRF guard blocks loopback URL');$blocked=false;try{UrlGuard::assertPublicHttpUrl('http://169.254.169.254/latest/meta-data');}catch(Throwable){$blocked=true;}$assert($blocked,'SSRF guard blocks cloud metadata address');
$runtime=new FileRuntimeStore($root.'/storage/cache/m7-test');$limiter=new RateLimiter($runtime);$assert($limiter->hit('test','client',2,60)['allowed'],'rate limiter permits request 1');$assert($limiter->hit('test','client',2,60)['allowed'],'rate limiter permits request 2');$assert(!$limiter->hit('test','client',2,60)['allowed'],'rate limiter blocks excess request');
$errors=new ErrorCenterService($store);$e=$errors->capture('M7_TEST','test error',['token'=>'should-not-persist','safe'=>'yes']);$assert(($e['context']['token']??'')==='[REDACTED]','Error Center redacts secret context');$errors->resolve((string)$e['id']);
$quota=new QuotaService($store);$qid=UuidV7::generate();$quota->record($qid,86,100);$assert(($quota->state($qid,100)['status']??'')==='quota_low','quota service enters quota_low state');
$views='';$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root.'/resources/views',FilesystemIterator::SKIP_DOTS));foreach($it as $f){if($f->isFile()&&$f->getExtension()==='php')$views.=file_get_contents($f->getPathname());}$assert(!str_contains($views,'onclick='),'views contain no inline onclick handlers');$assert(!\PuneMirror\Core\UrlGuard::isSafeMediaUrl('file:///etc/passwd'),'unsafe media URL scheme rejected');
echo "M7 smoke tests passed.\n";
