<header class="admin-top"><div><p>Acquisition</p><h1>Content Sources</h1></div><button class="admin-primary" data-open-source-form>+ Add source</button></header>
<section class="admin-panel"><table class="admin-table"><thead><tr><th>Name</th><th>Provider</th><th>Mode</th><th>Status</th><th>Quota</th><th>Credentials</th><th>Schedule</th><th>Actions</th></tr></thead><tbody>
<?php foreach($sources as $s):$q=$s['quota']??[];$creds=$s['credential_status']??[];?><tr>
<td><strong><?=pm_e($s['name']??'')?></strong><small><?=pm_e($s['handle']??'')?></small></td><td><?=pm_e(strtoupper($s['provider']??''))?></td><td><?=pm_e(strtoupper($s['classification_mode']??'review'))?></td>
<td><span class="status <?=pm_e($s['health_status']??'disabled')?>"><?=pm_e(strtoupper($s['health_status']??'disabled'))?></span><?php if(!empty($s['last_error'])):?><small class="error-text"><?=pm_e($s['last_error'])?></small><?php endif;?></td>
<td><small><?=number_format((int)($q['requests']??0))?> / <?=number_format((int)($q['soft_limit']??1000))?></small><span class="status <?=pm_e($q['status']??'healthy')?>"><?=pm_e(strtoupper($q['status']??'healthy'))?></span></td>
<td><?php if($creds):foreach($creds as $n=>$m):?><small><?=pm_e($n)?> <?=pm_e($m)?></small><?php endforeach;else:?><small>None in vault</small><?php endif;?><button data-open-credential="<?=pm_e($s['id'])?>">Set secret</button></td>
<td><?=!empty($s['sync_enabled'])?'Every '.(int)($s['sync_interval']??300).'s':'Manual'?></td><td class="admin-actions"><button data-source-test="<?=pm_e($s['id'])?>">Test</button><button data-source-sync="<?=pm_e($s['id'])?>">Sync</button></td>
</tr><?php endforeach;?></tbody></table></section>
<dialog class="admin-dialog" data-source-dialog><form method="dialog" data-source-form><h2>Add source</h2><label>Provider<select name="provider"><option>manual</option><option>wordpress</option><option>instagram</option><option>youtube</option><option>x</option></select></label><label>Name<input name="name" required></label><label>Handle<input name="handle"></label><label>Site URL (WordPress only)<input name="site_url" type="url" placeholder="https://example.com"></label><label>Sync interval<input name="sync_interval" type="number" value="300" min="60"></label><label>Daily soft quota<input name="quota_soft_limit" type="number" value="1000" min="1"></label><label><input type="checkbox" name="sync_enabled"> Automatic sync</label><div class="dialog-actions"><button value="cancel">Cancel</button><button class="admin-primary" value="default" data-create-source>Create</button></div></form></dialog>

<dialog class="admin-dialog" data-credential-dialog><form method="dialog" data-credential-form><h2>Store encrypted credential</h2><input type="hidden" name="source_id"><label>Credential name<select name="credential_name"><option value="access_token">Instagram access_token</option><option value="api_key">YouTube api_key</option><option value="bearer_token">X bearer_token</option></select></label><label>Secret value<input name="credential_value" type="password" autocomplete="new-password" required></label><p class="admin-help">The value is encrypted with APP_KEY and is never displayed again.</p><div class="dialog-actions"><button value="cancel">Cancel</button><button class="admin-primary" value="default" data-save-credential>Encrypt & save</button></div></form></dialog>
